# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 447540cc4abc5ed248fe2fcc716e44de6a9b0492e99f559ab04a37b22159a09d4ff98cb03d69dcefe7a08ad665c6b60e9c126bc8cb9f8ff18f3fce47a39ed6c9

test:
  secret_key_base: 06c401813b4b0bcaee695b466be8d0d7e615cd68207cbb0c30b50836a2553b817d9907e050e724406bfda87d744f2bc1345e23cbcb98af65b375225402d79059

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
